# This is a basic workflow to help you get started with Actions

name: INPU

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
          MARKET_IP:
            description: 'Provide Market IP'     
            required: true
            type: string
          SYMBOL_NAME:
            description: 'Provide only symbol name: XXXX'     
            required: true
            type: string
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Add as Secret
    - uses: gliech/create-github-secret-action@v1
      with:
        # name: ${{format('TESTNET_PAIR_NAME={0}-PERP',github.event.inputs.SYMBOL_NAME) }}
        name: ${{github.event.inputs.SYMBOL_NAME }}
        value: Eternia
        pa_token: ${{ secrets.PA_TOKEN }}
